{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dcf60c9d-a6ac-4ad2-812d-acf08d46bb58",
   "metadata": {},
   "outputs": [],
   "source": [
    "project:\n",
    "  type: website\n",
    "\n",
    "website:\n",
    "  title: \"Global Income Inequality Dashboard\"\n",
    "  navbar:\n",
    "    left:\n",
    "      - href: index.qmd\n",
    "        text: Home\n",
    "\n",
    "format:\n",
    "  html:\n",
    "    theme: flatly\n",
    "    css: styles.css\n",
    "    toc: true\n",
    "    toc-location: left"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
